default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 12345
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: auth_development

test:
  <<: *default
  database: auth_test

production:
  <<: *default
  database: auth_production